tickers:
  # Minimal universe for debugging VIX hanging issue
  - VOLV-B.ST     # Volvo B (Swedish Industrial)
  - SEB-A.ST      # SEB A (Swedish Bank)
  - GOOGL         # Alphabet (US Tech)
  - DUNI.ST       # Duni (Swedish Consumer)
  - NVDA          # NVIDIA (US Tech)
