tickers:
  # Swedish Large Cap
  - VOLV-B.ST     # Volvo B
  - SEB-A.ST      # SEB A
  - SWED-A.ST     # Swedbank A
  - SHB-A.ST      # Handelsbanken A
  - ATCO-A.ST     # Atlas Copco A
  - ATCO-B.ST     # Atlas Copco B
  - ABB.ST        # ABB
  - SAND.ST       # Sandvik
  - SKF-B.ST      # SKF B
  - ERIC-B.ST     # Ericsson B
  - TEL2-B.ST     # Tele2 B
  - HM-B.ST       # H&M B
  - ESSITY-B.ST   # Essity B
  - AZN.ST        # AstraZeneca
  - EQT.ST        # EQT
  - BOL.ST        # Boliden
  - ALFA.ST       # Alfa Laval
  - NIBE-B.ST     # NIBE B
  - ASSA-B.ST     # ASSA ABLOY B
  - LIFCO-B.ST    # Lifco B
  - INVE-B.ST     # Investor B
  - KINV-B.ST     # Kinnevik B
  - INDU-C.ST     # Industrivärden C
  - SAAB-B.ST     # Saab B
  - EPI-A.ST      # Epiroc A
  - HEXA-B.ST     # Hexagon B
  - EVO.ST        # Evolution Gaming
  - NDA-SE.ST     # Nordea
  - DUNI.ST       # Duni
  - CLAS-B.ST     # Clas Ohlson B
  - ELUX-B.ST     # Electrolux B
  - ENEA.ST       # Enea
  - CEVI.ST       # Cevian Capital

  # US Tech Giants
  - GOOGL         # Alphabet
  - MSFT          # Microsoft
  - NVDA          # NVIDIA
  - AAPL          # Apple
  - META          # Meta
  - AMZN          # Amazon
  - TSLA          # Tesla

  # Additional diversification
  - QQQ           # Nasdaq ETF
  - SPY           # S&P 500 ETF
  - IWM           # Russell 2000 ETF
  - EFA           # International ETF
